#!/usr/bin/env python
# -*- coding: Latin-1 -*-

"""
Full House

Scritto da Marco Beri <mberi@linkgroup.it>
Basato su un'idea di Erich Friedman <efriedma@stetson.edu>

fullhouse_engine.py: motore del gioco
fullhouse_problemi.py: lista dei problemi da risolvere
fullhouse.py: interfaccia grafica

"""

from fullhouse_engine import Scacchiera, Posizione

Problemi = (
    Scacchiera(5, (Posizione(0, 3),
                   Posizione(0, 4),
                   Posizione(4, 4))),
    Scacchiera(5, (Posizione(0, 2),
                   Posizione(3, 3),
                   Posizione(4, 1))),
    Scacchiera(5, (Posizione(0, 4),
                   Posizione(3, 2),
                   Posizione(4, 0))),
    Scacchiera(5, (Posizione(0, 0),
                   Posizione(1, 0),
                   Posizione(2, 3),
                   Posizione(4, 2))),
    Scacchiera(5, (Posizione(0, 0),
                   Posizione(2, 1),
                   Posizione(3, 4),
                   Posizione(4, 2))),
    Scacchiera(5, (Posizione(0, 0),
                   Posizione(0, 1),
                   Posizione(0, 2),
                   Posizione(4, 3),
                   Posizione(4, 4))),

    Scacchiera(6, (Posizione(0, 3),
                   Posizione(1, 3),
                   Posizione(4, 1))),
    Scacchiera(6, (Posizione(0, 0),
                   Posizione(1, 2),
                   Posizione(0, 4),
                   Posizione(0, 5),
                   Posizione(3, 5))),
    Scacchiera(6, (Posizione(0, 0),
                   Posizione(2, 1),
                   Posizione(1, 4),
                   Posizione(5, 4),
                   Posizione(5, 5))),
    Scacchiera(6, (Posizione(0, 2),
                   Posizione(1, 4),
                   Posizione(3, 0),
                   Posizione(3, 1),
                   Posizione(5, 2))),
    Scacchiera(6, (Posizione(0, 2),
                   Posizione(1, 4),
                   Posizione(3, 1),
                   Posizione(4, 1))),
    Scacchiera(6, (Posizione(1, 1),
                   Posizione(4, 3),
                   Posizione(5, 0),
                   Posizione(5, 3))),
    Scacchiera(6, (Posizione(0, 0),
                   Posizione(0, 5),
                   Posizione(2, 1),
                   Posizione(3, 3))),
    Scacchiera(6, (Posizione(0, 0),
                   Posizione(0, 5),
                   Posizione(1, 2),
                   Posizione(4, 4),
                   Posizione(5, 2))),
    Scacchiera(6, (Posizione(1, 1),
                   Posizione(2, 1),
                   Posizione(2, 5),
                   Posizione(4, 2),
                   Posizione(4, 3),
                   Posizione(5, 5))),

    Scacchiera(7, (Posizione(0, 0),
                   Posizione(1, 2),
                   Posizione(2, 4),
                   Posizione(3, 2),
                   Posizione(4, 2),
                   Posizione(6, 4))),
    Scacchiera(7, (Posizione(0, 6),
                   Posizione(1, 3),
                   Posizione(1, 4),
                   Posizione(3, 4),
                   Posizione(4, 2),
                   Posizione(5, 4))),
    Scacchiera(7, (Posizione(0, 6),
                   Posizione(1, 4),
                   Posizione(2, 1),
                   Posizione(2, 2),
                   Posizione(4, 2))),
    Scacchiera(7, (Posizione(0, 4),
                   Posizione(1, 2),
                   Posizione(5, 1),
                   Posizione(5, 6),
                   Posizione(6, 6))),
    Scacchiera(7, (Posizione(1, 4),
                   Posizione(1, 5),
                   Posizione(3, 6),
                   Posizione(4, 2),
                   Posizione(5, 5))),
    Scacchiera(7, (Posizione(1, 2),
                   Posizione(3, 1),
                   Posizione(5, 4),
                   Posizione(6, 6))),
    Scacchiera(7, (Posizione(2, 2),
                   Posizione(2, 4),
                   Posizione(3, 2),
                   Posizione(4, 5),
                   Posizione(5, 1))),
    Scacchiera(7, (Posizione(0, 0),
                   Posizione(0, 1),
                   Posizione(1, 3),
                   Posizione(2, 5),
                   Posizione(3, 3))),
    Scacchiera(7, (Posizione(3, 1),
                   Posizione(4, 4),
                   Posizione(4, 5),
                   Posizione(5, 4),
                   Posizione(6, 6))),

    Scacchiera(8, (Posizione(0, 7),
                   Posizione(2, 6),
                   Posizione(3, 1),
                   Posizione(5, 2),
                   Posizione(5, 3))),
    Scacchiera(8, (Posizione(0, 0),
                   Posizione(1, 6),
                   Posizione(2, 1),
                   Posizione(3, 7),
                   Posizione(4, 5))),
    Scacchiera(8, (Posizione(0, 2),
                   Posizione(1, 4),
                   Posizione(3, 0),
                   Posizione(4, 0),
                   Posizione(5, 2))),

    Scacchiera(9, (Posizione(1, 3),
                   Posizione(2, 5),
                   Posizione(5, 0),
                   Posizione(6, 6),
                   Posizione(7, 1))),
    Scacchiera(9, (Posizione(4, 1),
                   Posizione(4, 2),
                   Posizione(4, 3),
                   Posizione(6, 2),
                   Posizione(7, 4),
                   Posizione(8, 6))),
    Scacchiera(9, (Posizione(1, 1),
                   Posizione(1, 2),
                   Posizione(4, 4),
                   Posizione(6, 2),
                   Posizione(7, 4),
                   Posizione(7, 5))),
    )
